### ISSUE TITLE
Can't proceed with the installation.

### ISSUE THREAD

**Issue by Doomwhite** [ritschmaster/w32bindkeys#5]
I'm stuck at the "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/mingw64/lib/pkgconfig" part, when I try the "./autogen.sh" command, it says no such file, I've searched my entire storage for that file and can't find it.

**Comment by ritschmaster** [comment]
I literally have no idea what you are trying to achieve nor what you are experiencing. Please state the following:
1. On which OS are you doing all of that?
2. What do you mean by "no such file". Is your shell not finding the script or is the script stating that it cannot find something?

**Comment by Doomwhite** [comment]
Er.. In windows, right? Isn't this the whole point of the rep? Anyhow, I was doing the installation steps in the msys2 shell and found that problem after executing "./autogen.sh", it said it couldn't find any file of that name, I also tried searching my entire with the Everything software and found no file called .autogen, so it didn't generated...

**Comment by ritschmaster** [comment]
Since it is possible to cross-compile it is not obvious for me on what you are up to.

First: I strongly recommend sticking with a release if you do not intend to join the w32bindkeys development.

Second: I have not explicitly stated in the readme that you have to clone/download the repository first. After you have performed the per-requisites (installing msys2 + build dependencies) you have to `cd` into my cloned git repo to build it. I will update the readme accoringly.
